app = "hlatex" # Bạn có thể thay đổi tên ứng dụng

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
  FLY_APP_NAME = "true"
  PYTHON_VERSION = "3.10.0"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
