services:
  - type: web
    name: hlatex
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.10.0
